# Generated by Django 5.1.7 on 2025-04-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_financialsupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('faculty', models.CharField(max_length=100)),
                ('ects_amount', models.PositiveIntegerField()),
                ('domicile', models.CharField(max_length=255)),
                ('annual_family_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cadastral_income_rental', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cadastral_income_business', models.DecimalField(decimal_places=2, max_digits=12)),
                ('separable_taxable_incomes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alimentation_money', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('living_wages', models.DecimalField(decimal_places=2, max_digits=12)),
                ('income_replacement_allowance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('foreign_incomes', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
