# Generated by Django 5.1.7 on 2025-04-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punten_leefeenheid', models.IntegerField()),
                ('min_inkomensgrens', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_inkomensgrens', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie_4', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='living_unit_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
