# Generated by Django 5.1.7 on 2025-04-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_incomethreshold_userprofile_living_unit_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='study_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
