# Generated by Django 5.1.7 on 2025-04-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_question_text_question_text_question_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_category', models.IntegerField()),
                ('max_category', models.IntegerField()),
            ],
        ),
    ]
