# Generated by Django 5.1.7 on 2025-04-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_historicaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldata',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='category',
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='financial_aid_grant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='financial_aid_scholarship',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='study_expenses_books',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='study_expenses_housing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='study_expenses_tuition',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
