# Generated by Django 5.1.7 on 2025-04-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_historicaldata_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportsystem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
