# Generated by Django 5.1.7 on 2025-04-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_supportsystem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportsystem',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
