# Generated by Django 5.1.7 on 2025-04-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_supportsystem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='laptop_purchased',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_room',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
