# Generated by Django 5.1.7 on 2025-05-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_userprofile_laptop_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportsystem',
            name='percentage_covered',
            field=models.IntegerField(default=0),
        ),
    ]
